"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-wj(4#4g#ffn%&)2%d(thsmt-z-&af^pju@#t#td)=h5_-4=kzm"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    'rest_framework',   
    'rest_framework.authtoken',
    'dj_rest_auth',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth.registration',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.twitter',
    'allauth.socialaccount.providers.google',
    'rest_framework_api_key',
    "com_adaptor",
    "notification",
    'accounts',
    "scraper",
    "blockchain_auth",
    'payment',
    'django_celery_beat',
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    'accounts.middleware.AccountsPermissionMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = (
    "accounts.backends.AccountsModelBackend",
    "accounts.backends.AccountsAuthenticationBackend",
    "accounts.backends.PhoneAuthenticationBackend",
)
AUTH_USER_MODEL = 'accounts.CustomUser'


ACCOUNT_ADAPTER= "accounts.adapter.CustomAllAuthAdapter"

INVITE_LINK= 'http://example.com/'

LOGIN_URL = 'https://127.0.0.1:8000/accounts/account-login/'


#payments 
PAYMENT_PROVIDER = 'stripe'  # or 'dwolla'

DWOLLA_ENVIRONMENT = 'sandbox'
DWOLLA_KEY = 'your_dwolla_key'
DWOLLA_SECRET = 'your_dwolla_secret'

STRIPE_KEY = 'your_stripe_public_key'
STRIPE_SECRET_KEY = 'your_stripe_secret_key'
STRIPE_REFRESH_URL = 'https://yourdomain.com/payment/refresh'
PAYMENT_STRIPE_RETURN_URL = 'https://yourdomain.com/payment/return'
STRIPE_WEBHOOK_SECRET = 'your_webhook_secret'

PROVIDER = {
    'dwolla': {
        'app_key': 'your_dwolla_key',
        'app_secret': 'your_dwolla_secret',
    },
    'stripe': {
        'api_key': 'your_stripe_public_key',
        'secret_key': 'your_stripe_secret_key',
    }
}

# Set your business and customer models
DEFAULT_BUSINESS_MODEL = 'accounts.Branch'
BUSINESS_MODEL = 'accounts.Branch'
DEFAULT_CUSTOMER_MODEL = 'accounts.CustomUser'
CUSTOMER_MODEL = 'accounts.CustomUser'

MIGRATION_MODULES = {
    'accounts': 'accounts.custom_migrations',
}

ACCOUNT_EMAIL_VERIFICATION = 'optional'

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email', 'username*', 'password1*', 'password2*']

ACCOUNT_SIGNUP_FIELDS = {
    "email": {"required": True},
    "username": {"required": False},
    "password1": {"required": True},
    "password2": {"required": True},
}

ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True